version: '3'

services:

    # Database Storage
    mysql:
        build:
            context: ./docker/mysql
            dockerfile: Dockerfile.mysql
        image: mysql-dev:1
        container_name: database-sample-dev
        volumes: 
            - datasql:/var/lib/mysql
        networks:
            - development
        ports:
            # HostPort:ContainerPort
            - "8079:8079"
        restart: always

    # Database Manager
    # adminer:
    #     image: adminer:4
    #     networks:
    #         - development
    #     ports:
    #         - "8080:8080"
    #     depends_on: 
    #         - mysql
    #         - postgres
    #     restart: always

    # # Notebook 
    jupyterlab:
        build:
            context: ./docker/jupyter
            dockerfile: Dockerfile.jupyter
        image: jupyterlab-dev:1
        container_name: notebook-dev
        volumes:
            - ./:/home/jovyan/work/ModelOps
        networks: 
            - development
        ports:
            - "8888:8888"
        depends_on: 
            - mlflow
        env_file: 
            - ./docker/jupyter/secrets.env

    # Tracking server
    mlflow:
        build:
            context: ./docker/mlflow
            dockerfile: Dockerfile.mlflow
        image: mlflow-dev:1
        container_name: tracking-server-dev
        volumes: 
            - mlflow:/mlflow
        ports:
            - "5000:5000"
        networks:
            - development
        depends_on: 
            - postgres
            - minio
        env_file:
            - ./docker/mlflow/secrets.env

    # Tracking backend database
    postgres:
        build:
            context: ./docker/postgres
            dockerfile: Dockerfile.postgres
        image: postgres-dev:1
        container_name: tracking-database-dev
        volumes:
            - datapostgres:/var/lib/postgresql/data
        networks: 
            - development
        ports: 
            - "5432:5432"
        restart: always

    # Tracking Artefact backend
    minio:
        build: 
            context: ./docker/minio
            dockerfile: Dockerfile.minio
        image: minio-dev:1
        container_name: tracking-artefact-dev
        volumes:
            - dataminio:/data
        networks: 
            - development
        ports:
            - "9000:9000"
        env_file:
            - ./docker/minio/secrets.env
        command: server /data

volumes:
    datasql:
    mlflow:
    datapostgres:
    dataminio:

networks: 
    development: