FROM postgres:12-alpine

LABEL MANTAINER="Ivan Nardini <ivan.nardini@sas.com>"

LABEL DESCRIPTION='Customized postgres database backend for the Mlflow tracking server (demo purpose)'

ENV POSTGRES_DB='mlflow'
ENV POSTGRES_USER='ivnard'
ENV POSTGRES_PASSWORD='Orion123'
ENV PGPASSWORD='Orion123'